[package]
name = "deskc-evalmir"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
withserde = ["serde", "mir/withserde", "types/withserde"]

[dependencies]
mir = { path = "../../components/deskc-06-mir", version = "0.0.0", package = "deskc-mir" }
types = { path = "../../components/deskc-types", version = "0.0.0", package = "deskc-types" }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
lexer = { path = "../../systems/deskc-01-lexer", version = "0.0.0", package = "deskc-lexer" }
parser = { path = "../../systems/deskc-02-parser", version = "0.0.0", package = "deskc-parser" }
hirgen = { path = "../../systems/deskc-03-hirgen", version = "0.0.0", package = "deskc-hirgen" }
typeinfer = { path = "../../systems/deskc-04-typeinfer", version = "0.0.0", package = "deskc-typeinfer" }
chumsky = "0.8.0"
