[package]
name = "deskc-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = { path = "../../components/ast", version = "0.1.0", package = "deskc-ast" }
ariadne = "0.1.3"
chumsky = { git = "https://github.com/ryo33/chumsky" }
uuid = "*"

[dev-dependencies]
matches = "0.1.9"
