[package]
name = "dworkspace-codebase"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deskc-ids = { path = "../../components/deskc-ids", version = "0.0.0", package = "deskc-ids" }
types = { path = "../deskc-types", version = "0.0.0", package = "deskc-types" }
ast = { path = "../deskc-ast", version = "0.0.0", package = "deskc-ast" }
hir = { path = "../deskc-hir", version = "0.0.0", package = "deskc-hir" }

uuid = "1.2"
