[package]
name = "deskc-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
link = { path = "../link", version = "0.1.0", package = "deskc-link" }
uuid = "0.8"
