[package]
name = "deskc-amirgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amir = { path = "../../components/amir", version = "0.1.0", package = "deskc-amir" }
thir = { path = "../../components/thir", version = "0.1.0", package = "deskc-thir" }
thiserror = "1.0.30"
types = { path = "../../components/types", version = "0.1.0", package = "deskc-types" }
