[workspace]
resolver = "2"
members = [
  "crates/deskc/libs/*",
  "crates/deskc/apps/*",
  "crates/deskc/systems/*",
  "crates/deskc/components/*",
  "crates/deskc/tests/*",
  "crates/dkernel/systems/*",
  "crates/dkernel/components/*",
  "crates/dkernel/adapters/*",
  "crates/desk-x/apps/*",
]
