[workspace]
resolver = "2"
members = [
  "crates/libs/*",
  "crates/apps/*",
  "crates/plugins/*",
  "crates/systems/*",
  "crates/components/*",
  "crates/adapters/*",
  "crates/tests/*",
]

# for smaller build size
[profile.release]
lto = "thin"
