[tasks.build-wasm]
command = "cargo"
args = ["build", "--bin", "desk-client", "--target", "wasm32-unknown-unknown", "--release", "--features", "web"]

[tasks.wasm-bindgen]
command = "wasm-bindgen"
args = ["--out-dir", ".public", "--target", "web", "target/wasm32-unknown-unknown/release/desk-client.wasm"]
dependencies = ["build-wasm"]

[tasks.wasm-serve]
command = "basic-http-server"
args = [".public"]
dependencies = ["wasm-bindgen"]

[tasks.check]
command = "cargo"
args = ["check", "-p", "desk-client", "--features", "native"]

[tasks.check-wasm]
command = "cargo"
args = ["check", "-p", "desk-client", "--target", "wasm32-unknown-unknown", "--features", "web"]

[tasks.test]
command = "cargo"
args = ["test", "--all-features"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--workspace", "--all-targets", "--all-features", "--", "-D", "warnings", "-W", "clippy::all"]

[tasks.deny]
command = "cargo"
args = ["deny", "--all-features", "check"]

[tasks.ci-check]
run_task = { name = ["check", "check-wasm", "test", "fmt-check", "clippy", "deny"] }

[tasks.clippy-fix]
command = "cargo"
args = ["clippy", "--workspace", "--all-targets", "--all-features", "--fix", "--allow-dirty", "--allow-staged", "-Z", "unstable-options", "--", "-D", "warnings", "-W", "clippy::all"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all"]

[tasks.fix]
run_task = { name = ["fmt", "clippy-fix"] }

[tasks.debugdump]
script = '''
cargo run -p desk-client --features debugdump,native
cat target/schedule_graph.dot | dot -Tsvg > target/schedule_graph.png
'''

[config]
default_to_workspace = false