[package]
name = "deskc"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ids = { path = "../../components/deskc-ids", version = "0.0.0", package = "deskc-ids" }
ast = { path = "../../components/deskc-ast", version = "0.0.0", package = "deskc-ast" }
hir = { path = "../../components/deskc-hir", version = "0.0.0", package = "deskc-hir" }
thir = { path = "../../components/deskc-thir", version = "0.0.0", package = "deskc-thir" }
mir = { path = "../../components/deskc-mir", version = "0.0.0", package = "deskc-mir" }
ty = { path = "../../components/deskc-type", version = "0.0.0", package = "deskc-type" }
codebase = { path = "../../components/dworkspace-codebase", version = "0.0.0", package = "dworkspace-codebase" }
minimalist = { path = "../deskc-syntax-minimalist", version = "0.0.0", package = "deskc-syntax-minimalist" }
hirgen = { path = "../../systems/deskc-hirgen", version = "0.0.0", package = "deskc-hirgen" }
typeinfer = { path = "../../systems/deskc-typeinfer", version = "0.0.0", package = "deskc-typeinfer" }
thirgen = { path = "../../systems/deskc-thirgen", version = "0.0.0", package = "deskc-thirgen" }
mirgen = { path = "../../systems/deskc-mirgen", version = "0.0.0", package = "deskc-mirgen" }

salsa = "0.16"
uuid = "1.2"
anyhow = "1.0"
thiserror = "1.0.37"
