[package]
name = "deskc"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deskc-ids = { path = "../../components/deskc-ids", version = "0.0.0", package = "deskc-ids" }
deskc-hir = { path = "../../components/deskc-03-hir", version = "0.0.0", package = "deskc-hir" }
deskc-thir = { path = "../../components/deskc-04-thir", version = "0.0.0", package = "deskc-thir" }
deskc-amir = { path = "../../components/deskc-05-amir", version = "0.0.0", package = "deskc-amir" }
deskc-mir = { path = "../../components/deskc-06-mir", version = "0.0.0", package = "deskc-mir" }
deskc-types = { path = "../../components/deskc-types", version = "0.0.0", package = "deskc-types" }

salsa = "0.16"
uuid = "1.2"
