[package]
name = "desk-window"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dkernel-components = { package = "dkernel-components", version = "0.0.0", path = "../dkernel-components" }
deskc-ids = { package = "deskc-ids", version = "0.0.0", path = "../deskc-ids" }
# FIXME: component depends system
dkernel = { package = "dkernel", version = "0.0.0", path = "../../systems/dkernel" }

bevy_ecs = "0.7"
uuid = "0.8"
