[package]
name = "desk-window"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dworkspace-codebase = { package = "dworkspace-codebase", version = "0.0.0", path = "../dworkspace-codebase" }
deskc-ids = { package = "deskc-ids", version = "0.0.0", path = "../deskc-ids" }
# FIXME: component depends system
dworkspace = { package = "dworkspace", version = "0.0.0", path = "../../systems/dworkspace" }

bevy_ecs = "0.8"
uuid = "1.2"
