[package]
name = "desk-window"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

[dependencies]
dworkspace-codebase = { package = "dworkspace-codebase", version = "0.0.0", path = "../dworkspace-codebase" }
deskc-ids = { package = "deskc-ids", version = "0.0.0", path = "../deskc-ids" }
# FIXME: component depends system
dworkspace = { workspace = true }

bevy_ecs = { workspace = true }
bevy_math = { workspace = true }
uuid = { workspace = true}
