[package]
name = "deskc-link"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
withserde = ["serde", "uuid/serde"]

[dependencies]
uuid = "0.8"
serde = { version = "1.0", features = ["derive"], optional = true }
