[package]
name = "deskc-mir"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

[dependencies]
types = { path = "../deskc-types", version = "0.0.0", package = "deskc-types" }
conc-types = { path = "../deskc-conc-types", version = "0.0.0", package = "deskc-conc-types" }
amir = { path = "../deskc-05-amir", version = "0.0.0", package = "deskc-amir" }
ids = { path = "../deskc-ids", version = "0.0.0", package = "deskc-ids" }
serde = { version = "1.0", features = ["derive"] }
