[package]
name = "deskc-thir"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ty = { path = "../deskc-type", version = "0.0.0", package = "deskc-type" }
ids = { path = "../deskc-ids", version = "0.0.0", package = "deskc-ids" }
dson = { path = "../dson", version = "0.0.0", package = "dson" }
