[package]
name = "deskc-amirgen"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ids = { path = "../../components/deskc-ids", version = "0.0.0", package = "deskc-ids" }
amir = { path = "../../components/deskc-05-amir", version = "0.0.0", package = "deskc-amir" }
thir = { path = "../../components/deskc-04-thir", version = "0.0.0", package = "deskc-thir" }
thiserror = "1.0.30"
types = { path = "../../components/deskc-types", version = "0.0.0", package = "deskc-types" }
