[package]
name = "deskc-amir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types", version = "0.1.0", package = "deskc-types" }
serde = { version = "1.0", features = ["derive"], optional = true }
