[package]
name = "deskc-amir"
version = "0.1.0"
edition = "2021"

[features]
withserde = ["serde", "link/withserde"]

[dependencies]
types = { path = "../types", version = "0.1.0", package = "deskc-types" }
link = { path = "../link", version = "0.1.0", package = "deskc-link" }
serde = { version = "1.0", features = ["derive"], optional = true }
