[package]
name = "deskc-type-inference"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hir = { path = "../../components/hir", version = "0.1.0", package = "deskc-hir" }
types = { path = "../../components/types", version = "0.1.0", package = "deskc-types" }
thiserror = "1.0.30"
chumsky = { git = "https://github.com/ryo33/chumsky" }

[dev-dependencies]
lexer = { path = "../../systems/lexer", version = "0.1.0", package = "deskc-lexer" }
parser = { path = "../../systems/parser", version = "0.1.0", package = "deskc-parser" }
hirgen = { path = "../../systems/hirgen", version = "0.1.0", package = "deskc-hirgen" }
