[package]
name = "deskc-typeinfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hir = { path = "../../components/hir", version = "0.1.0", package = "deskc-hir" }
types = { path = "../../components/types", version = "0.1.0", package = "deskc-types" }
file = { path = "../../components/file", version = "0.1.0", package = "deskc-file" }
thiserror = "1.0.30"

[dev-dependencies]
lexer = { path = "../../systems/01_lexer", version = "0.1.0", package = "deskc-lexer" }
parser = { path = "../../systems/02_parser", version = "0.1.0", package = "deskc-parser" }
hirgen = { path = "../../systems/03_hirgen", version = "0.1.0", package = "deskc-hirgen" }
chumsky = { git = "https://github.com/ryo33/chumsky" }
pretty_assertions = "1.0.0"
