[package]
name = "deskc-hirgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = { path = "../../components/ast", version = "0.1.0", package = "deskc-ast" }
file = { path = "../../components/file", version = "0.1.0", package = "deskc-file" }
hir = { path = "../../components/hir", version = "0.1.0", package = "deskc-hir" }
pretty_assertions = "1.0.0"
thiserror = "1.0.30"

[dev-dependencies]
lexer = { path = "../../systems/01_lexer", version = "0.1.0", package = "deskc-lexer" }
parser = { path = "../../systems/02_parser", version = "0.1.0", package = "deskc-parser" }
chumsky = "0.8.0"
