[package]
name = "deskc-thirgen"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ids = { path = "../../components/deskc-ids", version = "0.0.0", package = "deskc-ids" }
hir = { path = "../../components/deskc-hir", version = "0.0.0", package = "deskc-hir" }
thir = { path = "../../components/deskc-thir", version = "0.0.0", package = "deskc-thir" }
ty = { path = "../../components/deskc-type", version = "0.0.0", package = "deskc-type" }
thiserror = "1.0.37"

[dev-dependencies]
dson = { path = "../../components/dson", version = "0.0.0", package = "dson" }
deskc = { path = "../deskc", version = "0.0.0", package = "deskc" }
typeinfer = { path = "../../systems/deskc-typeinfer", version = "0.0.0", package = "deskc-typeinfer" }
chumsky = "0.8.0"
pretty_assertions = "1.3.0"
