[package]
name = "deskvm-miri"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

[dependencies]
mir = { path = "../../components/deskc-05-mir", version = "0.0.0", package = "deskc-mir" }
types = { path = "../../components/deskc-types", version = "0.0.0", package = "deskc-types" }
dprocess = { path = "../../components/deskvm-dprocess", version = "0.0.0", package = "deskvm-dprocess" }

serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
lexer = { path = "../../systems/deskc-01-lexer", version = "0.0.0", package = "deskc-lexer" }
parser = { path = "../../systems/deskc-02-parser", version = "0.0.0", package = "deskc-parser" }
hirgen = { path = "../../systems/deskc-03-hirgen", version = "0.0.0", package = "deskc-hirgen" }
typeinfer = { path = "../../systems/deskc-04-typeinfer", version = "0.0.0", package = "deskc-typeinfer" }
chumsky = "0.8.0"
