[package]
name = "deskc-concretizer"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amir = { path = "../../components/amir", version = "0.0.0", package = "deskc-amir" }
mir = { path = "../../components/mir", version = "0.0.0", package = "deskc-mir" }
types = { path = "../../components/types", version = "0.0.0", package = "deskc-types" }
