[package]
name = "deskc-thir2dson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thir = { path = "../../components/thir", version = "0.1.0", package = "deskc-thir" }
dson = { path = "../../components/dson", version = "0.1.0", package = "deskc-dson" }
