[package]
name = "deskc-typeinfer"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ids = { path = "../../components/deskc-ids", version = "0.0.0", package = "deskc-ids" }
hir = { path = "../../components/deskc-hir", version = "0.0.0", package = "deskc-hir" }
types = { path = "../../components/deskc-types", version = "0.0.0", package = "deskc-types" }
dson = { path = "../../components/dson", version = "0.0.0", package = "dson" }
errors = { path = "../../components/deskc-errors", version = "0.0.0", package = "deskc-errors" }

thiserror = "1.0.37"

[dev-dependencies]
deskc = { path = "../deskc", version = "0.0.0", package = "deskc" }
chumsky = "0.8.0"
ariadne = "0.1"
pretty_assertions = "1.3.0"
env_logger = "0.10.0"
