[package]
name = "deskc-thir"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types", version = "0.1.0", package = "deskc-types" }
link = { path = "../link", version = "0.1.0", package = "deskc-link" }
