[package]
name = "deskc-syntax-minimalist"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ids = { path = "../../components/deskc-ids", version = "0.0.0", package = "deskc-ids" }
ast = { path = "../../components/deskc-ast", version = "0.0.0", package = "deskc-ast" }
errors = { path = "../../components/deskc-errors", version = "0.0.0", package = "deskc-errors" }
dson = { path = "../../components/dson", version = "0.0.0", package = "dson" }

parol_runtime = { git = "https://github.com/jsinger67/parol", rev = "f0be5be6e37b9141eefe064055928bcef63318a5", features = ["auto_generation"] }
anyhow = "1.0"
thiserror = "1.0.38"
uuid = { version = "1.2", features = ["v4"] }

[build-dependencies]
parol = { git = "https://github.com/jsinger67/parol", rev = "f0be5be6e37b9141eefe064055928bcef63318a5" }

[dev-dependencies]
env_logger = "0.10.0"
pretty_assertions = "1.3.0"
