[package]
name = "desk-x"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

[features]
inspector = ["bevy-inspector-egui"]

[dependencies]
egui-plugin = { path = "../../plugins/desk-x-egui", version = "0.0.0", package = "desk-x-egui-plugin" }

bevy = "0.7"
bevy-inspector-egui = { version = "0.10.0", optional = true }
console_error_panic_hook = "0.1"
web-sys = "0.3.57"
