[package]
name = "dkernel"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
components = { path = "../../components/dkernel-components", version = "0.0.0", package = "dkernel-components" }
deskc-ids = { path = "../../components/deskc-ids", version = "0.0.0", package = "deskc-ids" }
deskc-types = { path = "../../components/deskc-types", version = "0.0.0", package = "deskc-types" }
deskc-ast = { path = "../../components/deskc-02-ast", version = "0.0.0", package = "deskc-ast" }
deskc-hir = { path = "../../components/deskc-03-hir", version = "0.0.0", package = "deskc-hir" }
deskc-lexer = { path = "../deskc-01-lexer", version = "0.0.0", package = "deskc-lexer" }
deskc-parser = { path = "../deskc-02-parser", version = "0.0.0", package = "deskc-parser" }
deskc-hirgen = { path = "../deskc-03-hirgen", version = "0.0.0", package = "deskc-hirgen" }
deskc-typeinfer = { path = "../deskc-04-typeinfer", version = "0.0.0", package = "deskc-typeinfer" }

salsa = { version = "0.17.0-pre.2", git = "https://github.com/ryo33/salsa.git", rev = "7a0e914ea1ca3c2a6d2be50cc47bc5f635dbef34" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.31"
bevy_ecs = "0.7"
downcast-rs = "1.2.0"

[dev-dependencies]
deskc-types = { path = "../../components/deskc-types", version = "0.0.0", package = "deskc-types" }

uuid = { version = "1.0", features = ["v4"] }
mry = "0.2.2"
