[package]
name = "deskc-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokens = { path = "../../components/tokens", version = "0.1.0", package = "deskc-tokens" }
ast = { path = "../../components/ast", version = "0.1.0", package = "deskc-ast" }
textual-diagnostics = { path = "../../components/textual-diagnostics", version = "0.1.0", package = "deskc-textual-diagnostics" }
chumsky = "0.8.0"

[dev-dependencies]
lexer = { path = "../../systems/01_lexer", version = "0.1.0", package = "deskc-lexer" }
