[package]
name = "dkernel"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dkernel-ast = { path = "../../components/ast", version = "0.0.0", package = "dkernel-ast" }
dkernel-file = { path = "../../components/file", version = "0.0.0", package = "dkernel-file" }
deskc-ids = { path = "../../../deskc/components/ids", version = "0.0.0", package = "deskc-ids" }
deskc-ast = { path = "../../../deskc/components/ast", version = "0.0.0", package = "deskc-ast" }
deskc-hir = { path = "../../../deskc/components/hir", version = "0.0.0", package = "deskc-hir" }
deskc-thir = { path = "../../../deskc/components/thir", version = "0.0.0", package = "deskc-thir" }
deskc-amir = { path = "../../../deskc/components/amir", version = "0.0.0", package = "deskc-amir" }
deskc-mir = { path = "../../../deskc/components/mir", version = "0.0.0", package = "deskc-mir" }
deskc-types = { path = "../../../deskc/components/types", version = "0.0.0", package = "deskc-types" }

uuid = "0.8"
salsa = "0.16.1"
