[package]
name = "deskc-evalmir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
withserde = ["serde", "mir/withserde", "types/serde"]

[dependencies]
mir = { path = "../../components/mir", version = "0.1.0", package = "deskc-mir" }
types = { path = "../../components/types", version = "0.1.0", package = "deskc-types" }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
lexer = { path = "../../systems/lexer", version = "0.1.0", package = "deskc-lexer" }
parser = { path = "../../systems/parser", version = "0.1.0", package = "deskc-parser" }
hirgen = { path = "../../systems/hirgen", version = "0.1.0", package = "deskc-hirgen" }
typeinfer = { path = "../../systems/typeinfer", version = "0.1.0", package = "deskc-typeinfer" }
chumsky = { git = "https://github.com/ryo33/chumsky" }
