[package]
name = "deskvm"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dprocess = { path = "../../components/deskvm-dprocess", version = "0.0.0", package = "deskvm-dprocess" }
ty = { path = "../../components/deskc-type", version = "0.0.0", package = "deskc-type" }

anyhow = "1.0"
parking_lot = { workspace = true }

[dev-dependencies]
uuid = { version = "1.3", features = ["v4"] }
mir = { path = "../../components/deskc-mir", version = "0.0.0", package = "deskc-mir" }
miri = { path = "../deskvm-miri", version = "0.0.0", package = "deskvm-miri" }
