[package]
name = "deskvm"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dprocess = { path = "../../components/deskvm-dprocess", version = "0.0.0", package = "deskvm-dprocess" }
types = { path = "../../components/deskc-types", version = "0.0.0", package = "deskc-types" }

anyhow = "1.0.66"
parking_lot = "0.12.1"

[dev-dependencies]
uuid = { version = "1.2.2", features = ["v4"] }
mir = { path = "../../components/deskc-05-mir", version = "0.0.0", package = "deskc-mir" }
miri = { path = "../deskvm-miri", version = "0.0.0", package = "deskvm-miri" }
