[package]
name = "deskc-parser"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ids = { path = "../../components/deskc-ids", version = "0.0.0", package = "deskc-ids" }
tokens = { path = "../../components/deskc-01-tokens", version = "0.0.0", package = "deskc-tokens" }
ast = { path = "../../components/deskc-02-ast", version = "0.0.0", package = "deskc-ast" }
textual-diagnostics = { path = "../../components/deskc-textual-diagnostics", version = "0.0.0", package = "deskc-textual-diagnostics" }

chumsky = "0.8.0"
uuid = "1.0"
thiserror = "1.0"

[dev-dependencies]
lexer = { path = "../../systems/deskc-01-lexer", version = "0.0.0", package = "deskc-lexer" }
