[package]
name = "deskc-hirgen"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ids = { path = "../../components/deskc-ids", version = "0.0.0", package = "deskc-ids" }
ast = { path = "../../components/deskc-ast", version = "0.0.0", package = "deskc-ast" }
hir = { path = "../../components/deskc-hir", version = "0.0.0", package = "deskc-hir" }
dson = { path = "../../components/dson", version = "0.0.0", package = "dson" }

pretty_assertions = "1.4.0"
thiserror = { workspace = true }

[dev-dependencies]
deskc = { path = "../deskc", version = "0.0.0", package = "deskc" }
chumsky = "0.9.2"
