[package]
name = "deskc-hirgen"
version = "0.0.0"
license = "MIT OR Apache-2.0"
description = "The application platform for your cyberpunk desk"
homepage = "https://github.com/Hihaheho/Desk"
repository = "https://github.com/Hihaheho/Desk"
readme = "../../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ids = { path = "../../components/deskc-ids", version = "0.0.0", package = "deskc-ids" }
ast = { path = "../../components/deskc-02-ast", version = "0.0.0", package = "deskc-ast" }
hir = { path = "../../components/deskc-03-hir", version = "0.0.0", package = "deskc-hir" }

pretty_assertions = "1.3.0"
thiserror = "1.0.37"
uuid = { version = "1.2", features = ["v4"] }

[dev-dependencies]
lexer = { path = "../../systems/deskc-01-lexer", version = "0.0.0", package = "deskc-lexer" }
parser = { path = "../../systems/deskc-02-parser", version = "0.0.0", package = "deskc-parser" }
chumsky = "0.8.0"
