name: CI
on:
  push:
    branches:
      - main
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # for alsa
      - run: sudo apt-get install --no-install-recommends libasound2-dev -y

      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - run: tools/check-ci.sh
