[package]
name = "deskc-lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokens = { path = "../../components/tokens", version = "0.1.0", package = "deskc-tokens" }
chumsky = { git = "https://github.com/ryo33/chumsky" }

uuid = "*"
